// The asset pipeline's palette: every hex each biome look uses (water, terrain, walls, roofs, accents, trees, walker
// colours, sky), read from src/view/biomes and written to tools/assets/palette.json for the Blender kits. The looks
// module is bundled with esbuild (Node's own resolver wants file extensions the sources don't carry), and the
// bundle is refused if it would pull Babylon at runtime: the palette is data, and so is everything it reads.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
export const PALETTE_JSON = join(HERE, "palette.json");

interface LookLike {
  id: string;
  water: Record<string, string>;
  terrain: Record<string, string | number>;
  lagoon: { tint: string };
  sky: { fogTint: string };
  walls: readonly string[];
  roofs: readonly string[];
  accents: Record<string, string>;
  walker: { colors: readonly string[] };
  trees: { trunk: string; leaves: readonly string[] };
  boat: string;
  trees_kit?: string;
}

/** Every look, as plain data, from the game's own module. */
export async function readLooks(): Promise<LookLike[]> {
  const out = await build({ entryPoints: [join(ROOT, "src/view/biomes/index.ts")], bundle: true, format: "esm", platform: "neutral", write: false, logLevel: "silent" });
  const code = out.outputFiles[0].text;
  if (/@babylonjs/.test(code)) throw new Error("the looks module pulls Babylon at runtime; the palette must read data only");
  const mod = await import("data:text/javascript;base64," + Buffer.from(code).toString("base64")) as { lookOf(id: string): LookLike };
  return ["tidewater", "fjord", "atoll"].map(id => mod.lookOf(id));
}

const hex = (v: unknown): v is string => typeof v === "string" && /^#[0-9a-fA-F]{6}$/.test(v);

/** The palette document: per look, the hexes by role, plus the flat set a kit may paint with. */
export async function palette(): Promise<Record<string, unknown>> {
  const looks = await readLooks();
  const doc: Record<string, unknown> = { note: "Generated by tools/assets/palette.ts from src/view/biomes. Do not edit.", looks: {} };
  for (const l of looks) {
    const terrain: Record<string, string> = {};
    for (const [k, v] of Object.entries(l.terrain)) if (hex(v)) terrain[k] = v.toLowerCase();
    const entry = {
      water: Object.fromEntries(Object.entries(l.water).map(([k, v]) => [k, v.toLowerCase()])),
      terrain,
      lagoon: l.lagoon.tint.toLowerCase(),
      sky: l.sky.fogTint.toLowerCase(),
      walls: l.walls.map(c => c.toLowerCase()),
      roofs: l.roofs.map(c => c.toLowerCase()),
      accents: Object.fromEntries(Object.entries(l.accents).map(([k, v]) => [k, v.toLowerCase()])),
      trees: { trunk: l.trees.trunk.toLowerCase(), leaves: l.trees.leaves.map(c => c.toLowerCase()) },
      walker: l.walker.colors.map(c => c.toLowerCase()),
      boat: l.boat,
    };
    const all = new Set<string>();
    const walk = (v: unknown): void => { if (hex(v)) all.add(v.toLowerCase()); else if (Array.isArray(v)) v.forEach(walk); else if (v && typeof v === "object") Object.values(v).forEach(walk); };
    walk(entry);
    (doc.looks as Record<string, unknown>)[l.id] = { ...entry, all: [...all].sort() };
  }
  return doc;
}

/** Write palette.json; returns whether its content changed. */
export async function writePalette(): Promise<boolean> {
  const text = JSON.stringify(await palette(), null, 2) + "\n";
  let before = "";
  try { before = readFileSync(PALETTE_JSON, "utf8"); } catch { /* first run */ }
  writeFileSync(PALETTE_JSON, text);
  return before.replace(/\r\n/g, "\n") !== text;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const changed = await writePalette();
  console.log(`[assets] palette.json ${changed ? "written (changed)" : "unchanged"}`);
}
